### ISSUE TITLE
error when run npm run make

### ISSUE THREAD

**Issue by nictronik99** [GSWXXN/NFCToolsGUI#5]
An unhandled rejection has occurred inside Forge:
Error: Command failed: git rev-parse --short HEAD
fatal: not a git repository (or any of the parent directories): .git
at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at Proxy.generateAssets (C:\Users\myname\Downloads\NFCToolsGUI-main\forge.config.js:43:26)
    at Task.task (C:\Users\myname\Downloads\NFCToolsGUI-main\node_modules\@electron-forge\core\dist\util\hook.js:33:42)
    at Task.run (C:\Users\myname\Downloads\NFCToolsGUI-main\node_modules\listr2\dist\index.cjs:978:35)

**Comment by ygrekconsutling** [comment]
got an error too in the npm make one debian:
An unhandled rejection has occurred inside Forge:
Error: spawn zip ENOENT
at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

any news?

**Comment by 19e2k67** [comment]
@nictronik99 You need to clone the repository instead of downloading the source code.[Cloning a repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository#cloning-a-repository)

then [Compile the core component](https://github.com/GSWXXN/NFCToolsGUI?tab=readme-ov-file#compile-the-core-component), and then [Compile GUI](https://github.com/GSWXXN/NFCToolsGUI?tab=readme-ov-file#compile-gui)

**Comment by nictronik99** [comment]
> @nictronik99 You need to clone the repository instead of downloading the source code.[Cloning a repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository#cloning-a-repository)
> 
> then [Compile the core component](https://github.com/GSWXXN/NFCToolsGUI?tab=readme-ov-file#compile-the-core-component), and then [Compile GUI](https://github.com/GSWXXN/NFCToolsGUI?tab=readme-ov-file#compile-gui)
> 

Thank you very much
